### ISSUE TITLE
Create all HTML pages for stepping stone 1

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#28]
We need the following pages:

* all users
    - [x] login page
* researchers
    - [x] workspace list page
    - [X] workspace file browser page
    - [x] request list page (added in #41)
    - [x] request file browser page: (added in #33)
  
* reviewers
    - [x] request list page (added in #41)
    - [x] request file browser page (added in #33)

We need the following components somewhere:

(The below are all added in #33)

* researchers
    - [x] "add to request" button (or "include in request" toggle?)
    - [x] "submit request"
* reviewers
    - [x] "release request" / "approve request" buttons

**Comment by bloodearnest** [comment]
As implemented in #33, the UIs for viewing a workspace and a request are the same templates.

There is some conditional logic to show or hide buttons based on user permissions, but that's it.

**Comment by bloodearnest** [comment]
#41 adds list pages for workspaces and requests.
